[package]
name = "ivae"
version = "0.1.0"
authors = ["June Elva"]
edition = "2021"

[dependencies]
glyphon = "0.5.0"
pollster = "0.3.0"
wgpu = "0.19"
winit = { version = "0.29.10", features = ["rwh_05"] }
